image: gcc:latest

stages:
- build_main
- test_main

before_script:
  - apt update && apt-get install -y gcc openjdk-8-jdk
  - export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"

x86_build:
  stage: build_main
  script:
  - ./gradlew assemble
  tags:
  - x86_64

x86_test:
  stage: test_main
  script:
  - ./gradlew test jacocoTestReport
  - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  tags:
  - x86_64