stages:
- build_main
- test_main
- build_others
- test_others

x86_build:
  stage: build_main
  script:
  - cd java2c/
  - ./gradlew assemble
  tags:
  - x86_64_linux

x86_test:
  stage: test_main
  script:
  - cd java2c/
  - ./gradlew test
  tags:
  - x86_64_linux

arm_build:
  stage: build_others
  script:
  - cd java2c/
  - ./gradlew assemble
  tags:
  - armv6

arm_test:
  stage: test_others
  script:
  - cd java2c/
  - ./gradlew test
  tags:
  - armv6
