stages:
- build
- test

x86_build:
  stage: build
  script:
  - cd java2c/
  - ./gradlew assemble
  tags:
  - x86_64_linux

x86_test:
  stage: test
  script:
  - cd java2c/
  - ./gradlew test
  tags:
  - x86_64_linux

arm_build:
  stage: build
  script:
  - cd java2c/
  - ./gradlew assemble
  tags:
  - armv6

arm_test:
  stage: test
  script:
  - cd java2c/
  - ./gradlew test
  tags:
  - armv6
