stages:
- build_main
- test_main

x86_build:
  stage: build_main
  script:
  - ./gradlew assemble
  tags:
  - x86_64

x86_test:
  stage: test_main
  script:
  - ./gradlew test jacocoTestReport
  - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  tags:
  - x86_64