language: c
script:
    - mkdir -p build
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..
    - cmake --build .
    - ./apk2c-testsuite
    - cd CMakeFiles/apk2c-testsuite.dir/src
    - gcov *
after_success:
    - bash <(curl -s https://codecov.io/bash)
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
          before_install: 
            - sudo apt-get update -q
            - sudo apt-get install libzip-dev libcmocka-dev -y
          compiler: gcc
        - os: linux
          dist: trusty
          sudo: true
          before_install:
              - sudo apt-get update -q
              - sudo apt-get install libzip-dev libcmocka-dev -y
          compiler: clang
        - os: osx
          before_install:
              - brew update
              - brew install libzip cmocka
          compiler: clang
