name: CI

on: [pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run gradle assemble
        run: ./gradlew assemble

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run gradle test
        run: ./gradlew test --fail-fast
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Java2C test results
          path: java2c/build/reports/tests
